---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install ont-guppy
  package:
    name: ont-guppy
    state: present
  notify: restart guppyd
  ignore_errors: "{{ ansible_check_mode }}"
  when: ont_install_minKNOW is false

- include_tasks: install-minknow-guppy-gpu.yml
  when: ont_install_minKNOW is true and not already_installed.stat.exists
